### ISSUE TITLE
Rename reducable to reducible

### ISSUE THREAD

**Issue by eksperimental** [Qqwy/elixir-fun_land#25]
**reducible**
_adjective_
able to be made simpler, or smaller in size, amount, degree, importance, etc.:

**Comment by Qqwy** [comment]
Ah! I make a typo in the original name?! :sweat_smile: 

Thank you very much for pointing that out. :green_heart: 
This will be a straightforward but unfortunately backwards-incompatible change. Time for a version `0.10`.

**Comment by eksperimental** [comment]
I can submit a PR.
There is another backward incompatible change also. but that is another issue that I will publish later on.
