### ISSUE TITLE
`use Reducible` should allows user not to define to_list/1 function 

### ISSUE THREAD

**Issue by eksperimental** [Qqwy/elixir-fun_land#27]
When making my own Array implementation, I had to comment this line
https://github.com/Qqwy/elixir-arrays/blob/master/lib/arrays/implementations/map_array.ex#L27
`use Reducable`

because I wanted to define my own implementation of `to_list/1`.
Having an option not to define it would be ideal.

**Comment by Qqwy** [comment]
Ah! That indeed would be a good idea.

I think one simple approach would be to add a `defoverridable` at the bottom of Reducable/(Reducible :stuck_out_tongue_winking_eye: ).

**Comment by eksperimental** [comment]
Once the PR that renames reducable is merged, I will submit this one
